
const strings = {

  CAMBIO_GUARDADO: "Cambio Guardado!",
  CAMPOS_VACIOS:"Campos vacíos",
  CANCELAR:"Cancelar",
  CAMARA:"Cámara",
  BUSCAR:"Buscar",
  COTIZACION:"Cotización",
  PEDIDO:"Pedido",
  VENTA_STOCK:"Venta Stock",
  VENTA_PEDIDO:"Venta Pedido",
  VENTA_MOSTRADOR:"Venta Mostrador",
  VENTA_PERDIDA:"Venta Perdida",
  PETICION_HECHA: "Peticion hecha correctamente.",
  NO_BUSQUEDA:"La busqueda no dio resultados",
  REINTENTAR:"Intente de nuevo",
  INTENTAR_DE_NUEVO:"Intentar de nuevo con valores diferentes",
  OCURRIO_ERROR:"Ocurrio un error",
  DOCUMENTO:"Documento",
  MONTO:"Monto",
  PRECIO:"Precio",
  TOTAL:"Total",
  SALDO:"Saldo",
  FECHA:"Fecha",
  LLEGA:"LLega",
  FACTURA:"Factura",
  EL_DOCUMENTO_GENERADO_EXITO:"El documento fue generado con éxito",
  DOCUMENTO_GENERADO_EXITO:"Documento generado con éxito",
  DOCUMENTO_EXITO:"Documento enviado con éxito",
  DOCUMENTO_EXITO_ENVIO_CLIENTE:"El documento se envío con éxito al cliente",
  ERROR:"error",
  ERROR_TERMOMETRO:"Error al actualizar el termometro y las observaciones",
  VISTA_NO_DISPONIBLE:"Vista no disponible",
  VERSION_PRUEBAS:"Versión de pruebas",
  REQUISICION_SOLICITADA:"Requisicion solicitada",
  GENERAR_ORDEN_PRODUCCION:"Generar O Produccion",
  EXISTE_PROBLEMA:"Existe un problema",
  PROBLEMA_LOGIN:"Existe un problema con el correo o password, intente de nuevo",
  PROBLEMA_SERVIDOR:"Existe un problema con el servidor, intentelo más tarde ",
  CERRAR_SESION:"¿Quieres cerrar tu sesiòn?",
  COTIZACION_EXITO:"Cotización creada con éxito",
  PEDIDO_EXITO:"Pedido creado con éxito",
  MOV_EXITO:"Movimiento creado con éxito",
  SI:"Si",
  NO:"No",
  OK:"Ok",
  IF1:"if1",
  IF2:"if2",
  IF3:"if3",
  IF4:"if4",
  INICIO:"INICIO",
  HOY:"HOY",
  ARTICULOS:"ARTÍCULOS",
  CLIENTES:"CLIENTES",
  CARRITO:"CARRITO",
  SEGUIMIENTO:"SEGUIMIENTO",
  ULTIMOS:"ULTIMOS",
  INFORMACION_INVALIDA:"Información inválida",
  SIN_USUARIO:"Su usuario no presenta empresa, nombre o sucursal",
  SUCURSAL:"Sucursal",
  INGRESAR:"Ingresar",
  EMPEZAR:"Empezar",
  USUARIO:"Usuario",
  FECHA_EMISION:"Fecha de Emisión",
  USUARIO_INCORRECTO:"Usuario incorrecto",
  INFORMACION_INCORRECTA:"Usuario o contraseña incorrecta",
  CONTRASENA_INCORRECTA:"su contraseña es incorrecta, si no recuerdas tu contraseña ponte en contacto con tu supervisor",
  CODIGO_AUTORIZACION_APLICADO:"código de autorización ya aplicado",
  INICIA_SESION:"Inicia tu sesión",
  CONTRASENA:"Contraseña",
  INSERTAR_USUARIO:"Ingresar aquí tu usuario",
  INSERTAR_CONTRASENA:"Ingresar aquí tu contraseña",
  INSERTAR_CORREO:"Ingresa tu correo electrónico",
  CLAVE_DESCRIPCION:"Clave o Descripción",
  CLIENTE:"Cliente",
  RFC:"RFC",
  DIRECCION:"Dirección",
  N_EXTERIOR:"N° Exterior",
  N_INTERIOR:"N° Interior",
  CODIGO_POSTAL:"Código Postal",
  DELEGACION:"Delegación",
  COLONIA:"Colonia",
  POBLACION:"Población",
  ESTADO:"Estado",
  PAIS:"País",
  NOMBRE:"Nombre",
  CORREO:"Correo electrónico",
  TELEFONO_PRINCIPAL:"Teléfono principal",
  TELEFONO_CONTACTO:"Teléfono de contacto",
  nextText:'>',
  previousText: '<',
  loadingText: 'Cargando...',
  noDataText: 'Sin Resultados',
  pageText: 'Página',
  ofText: 'de',
  rowsText: 'Renglones',
  SALUDO_MENSAJE_WHATSAPP:"Hola, buen día. Adjunto la cotización de los muebles que vio en nuestra tienda.",
  LADA:"521",
  TELEFONO_CLIENTE_NO_CONFIGURADO:"El teléfono del cliente no parece estar configurado",
  ERROR_PDF:"Error al generar el pdf, contacte a su administrador",
  SUCCESS:"success",
  ARTICULO:"Artículo",
  ESCRIBE_NOTA_AQUI:"Escribe tu nota aqui...",
  DESCRIPCION:"Descripción",
  SIN_INFORMACION:"Sin información",
  PRECIO_REGULAR:"Precio Regular",
  PRECIO_MESES:"Precio Meses",
  PRECIO_CONTADO:"Precio Contado",
  CANTIDAD:"Cantidad",
  MOVIMIENTO:"Movimiento",
  ESTATUS:"Estatus",
  DESCUENTO:"Descuento Normal (%)",
  DESCUENTO_ESPECIAL:"Descuento Especial (%)",
  ALMACEN:"Almacén",
  QUE_HACER:"¿Qué desea hacer?",
  NOTAS:"Notas",
  ELIMINAR:"Eliminar",
  SEMANA:'No puede seleccionar una semana mayor a 52',
  CONDICIONAL:true,
  CONDICIONAL_PAGE_AUTORIZACION:0,
  IMPORTE:"Importe",
  ADVERTENCIA:"Advertencia",
  DIRECCION_MAC:"Dirección MAC",
  SIN_DESCUENTOS:"Sin descuentos",
  NOMBRE_CLIENTE:"Nombre del Cliente",
  VALOR_NO_VACIO:"El valor no puede estar vacío" 
};

export default strings;
